name: ROS Lint
on:
  pull_request:

jobs:
  ament_lint:
    name: ament_${{ matrix.linter }}
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        linter: [copyright, cppcheck, lint_cmake]
    steps:
    - uses: actions/checkout@v1
    - uses: ros-tooling/setup-ros@v0.2
    - uses: ros-tooling/action-ros-lint@v0.1
      with:
        distribution: jazzy
        linter: ${{ matrix.linter }}
        package-name:
          smacc2

          cl_keyboard

          backward_global_planner
          backward_local_planner
          forward_global_planner
          forward_local_planner
          nav2z_planners_common
          pure_spinning_local_planner
          undo_path_global_planner
          cl_nav2z

          multirole_sensor_client
          cl_ros2_timer

          eg_conditional_generator
          eg_random_generator

          smacc2_msgs

          sm_advanced_recovery_1
          sm_atomic
          sm_atomic_http
          sm_atomic_lifecycle
          sm_atomic_mode_states
          sm_branching
          sm_cl_keyboard_unit_test_1
          sm_cl_ros2_timer_unit_test_1
          sm_multi_stage_1
          sm_pack_ml
          sm_panda_cl_moveit2z_cb_inventory
          sm_simple_action_client
          sm_three_some

          sr_all_events_go
          sr_conditional
          sr_event_countdown
